export { default as Navbar } from "./Navbar"
export { default as HeroSection } from "./HeroSection"
export { default as Benefit } from "./Benefit"
export { default as GenerateWebsite } from "./GenerateWebsite"
export { default as Pricing } from "./Pricing"
export { default as CallAction } from "./CallAction"
export { default as Footer } from "./Footer"
